name:                aoc201801
version:             0.1.0.0
github:              "mx781/aoc"
license:             BSD3
author:              "mx781"
maintainer:          "mx781"
copyright:           "2018 mx781"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/mx781/aoc#README>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  aoc201801-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc201801

tests:
  aoc201801-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc201801
    - HUnit
